version: "3.9"

services:
  cantina:
    image: ijimiguel/cantina:latest
    container_name: cantina
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MY_JSON_SERVER_URL: "{MY_JSON_SERVER_URL}"
      MY_JSON_SERVER_API: "{MY_JSON_SERVER_API_TOKEN}"